name: 0 Deploy PoC Env

on:
  workflow_dispatch:
  
env:
  AZURE_REGION: eastus2
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '6.0.x' 
  IGNITE2022MX_ARTIFACT: ignite2022mx-app
  AZURE_WEBAPP_NAME: wapp-oa01

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-resource-group:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure RG
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --location ${{ env.AZURE_REGION }} --name ${{ secrets.RESOURCE_GROUP_NAME }}
          
  create-infra-iac:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: create-resource-group
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep template
    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
        template: ./IaC/deploy-appservice.bicep
        # parameters: appName=<Type a unique name for yor webapp>
        parameters: ./IaC/parameters-appservice.json      
        
  continuous-integration:
    runs-on: windows-latest
    if: ${{ success() }}
    needs: create-infra-iac
    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IGNITE2022MX_ARTIFACT }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
          
    
  continuous-delivery:
    runs-on: windows-latest
    if: ${{ success() }}
    needs: continuous-integration
    environment:
      name: 'PoC Env'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
        # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.IGNITE2022MX_ARTIFACT }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
            
         # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout
          
    
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [continuous-delivery]
    steps:
      - name: create-issue
        uses: oaviles/issue_action@v1
        with:
          issue-title: "Deployment Failure: PoC Env - ${{ github.sha }}"
          issue-body: "Validate orchestration workflow"
          repo-token: ${{secrets.GITHUB_TOKEN}}  
